Import Necessary Libraries

In [13]:
import pandas as pd
import requests
import matplotlib.pyplot as plt

Check api response

In [17]:
response_API = requests.get('https://boardgamegeek.com/xmlapi/boardgame/251696')
print(response_API.status_code)

200

In [18]:
game_info_35424 = response_API.text
print(game_info_35424)

<boardgames termsofuse="https://boardgamegeek.com/xmlapi/termsofuse">
			<boardgame objectid="251696" subtypemismatch="true">
   <yearpublished></yearpublished>
   <minplayers></minplayers>
   <maxplayers></maxplayers>
   <playingtime></playingtime>
   <minplaytime></minplaytime>
   <maxplaytime></maxplaytime>
   <age></age>

   	   <name primary="true" sortindex="1">Emily Wants to Play Too</name>

   <description>User Summary&lt;br/&gt;&lt;br/&gt;Emily Wants to Play Too is a sequel to the original game, Emily Wants to Play.&lt;br/&gt;&lt;br/&gt;It was developed by Shawn Hitchcock.&lt;br/&gt;&lt;br/&gt;</description>

   	   <thumbnail>https://cf.geekdo-images.com/KL_CYsOwBtxNnSDsNZfTnA__thumb/img/9PRooKUNgQYobbHIwrJG770Rv7E=/fit-in/200x150/filters:strip_icc()/pic4101386.jpg</thumbnail>
	   <image>https://cf.geekdo-images.com/KL_CYsOwBtxNnSDsNZfTnA__original/img/PRA1CY8uxL6eZWyZzksfTd7D6tg=/0x0/filters:format(jpeg)/pic4101386.jpg</image>

   	   		   <videogamedeveloper objectid="14029">(Self-Developed Video Game)</videogamedeveloper>
      	   		   <videogamepublisher objectid="4">(Self-Published)</videogamepublisher>
      	   		   <videogamegenre objectid="2152">Adventure</videogamegenre>
      	   		   <videogametheme objectid="2265">Horror</videogametheme>
      	   		   <videogameplatform objectid="21674">PlayStation 4</videogameplatform>
      	   		   <videogameversion objectid="404057">Playstation 4 Downloadable edition</videogameversion>
      	   		   <videogamemode objectid="2149">Single-Player</videogamemode>
      	   		   <videogameplatform objectid="4977">Windows</videogameplatform>
      	   		   <videogameversion objectid="404056">Windows Downloadable edition</videogameversion>

   <poll name="suggested_numplayers" title="User Suggested Number of Players" totalvotes="0">

		<results numplayers="0+">
					<result value="Best" numvotes="0" />
					<result value="Recommended" numvotes="0" />
					<result value="Not Recommended" numvotes="0" />
				</results>
	</poll>
<poll-summary name="suggested_numplayers"  title="User Suggested Number of Players">
  <result name="bestwith" value="" />
  <result name="recommmendedwith" value="(no votes)" />
</poll-summary>

   <poll name="language_dependence" title="Language Dependence" totalvotes="0">

		<results>
					<result level="1" value="No necessary in-game text" numvotes="0" />
					<result level="2" value="Some necessary text - easily memorized or small crib sheet" numvotes="0" />
					<result level="3" value="Moderate in-game text - needs crib sheet or paste ups" numvotes="0" />
					<result level="4" value="Extensive use of text - massive conversion needed to be playable" numvotes="0" />
					<result level="5" value="Unplayable in another language" numvotes="0" />
				</results>
	</poll>

   <poll name="suggested_playerage" title="User Suggested Player Age" totalvotes="0">
			<results>
					<result value="2" numvotes="0" />
					<result value="3" numvotes="0" />
					<result value="4" numvotes="0" />
					<result value="5" numvotes="0" />
					<result value="6" numvotes="0" />
					<result value="8" numvotes="0" />
					<result value="10" numvotes="0" />
					<result value="12" numvotes="0" />
					<result value="14" numvotes="0" />
					<result value="16" numvotes="0" />
					<result value="18" numvotes="0" />
					<result value="21 and up" numvotes="0" />
				</results>
	</poll>






</boardgame>

</boardgames>

In [21]:
df_board_game_rankings = pd.read_csv('.\\.venv\\data\\boardgames_ranks.csv')
df_board_game_rankings.head()

,id,name,yearpublished,rank,bayesaverage,average,usersrated,is_expansion,abstracts_rank,cgs_rank,childrensgames_rank,familygames_rank,partygames_rank,strategygames_rank,thematic_rank,wargames_rank
0,224517,Brass: Birmingham,2018,1,8.41277,8.59213,48001,0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
1,161936,Pandemic Legacy: Season 1,2015,2,8.37571,8.52498,54148,0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN
2,174430,Gloomhaven,2017,3,8.34398,8.57972,63128,0,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN
3,342942,Ark Nova,2021,4,8.33959,8.53505,46382,0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
4,233078,Twilight Imperium: Fourth Edition,2017,5,8.23662,8.59240,24556,0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,NaN

In [30]:
nozerorank = df_board_game_rankings[(df_board_game_rankings['rank'] == 0)].index
df_bgr_nozerorank = pd.DataFrame(df_board_game_rankings.drop(nozerorank, inplace = True))
df_board_game_rankings.head(20)

Empty DataFrame
Columns: [id, name, yearpublished, rank, bayesaverage, average, usersrated, is_expansion, abstracts_rank, cgs_rank, childrensgames_rank, familygames_rank, partygames_rank, strategygames_rank, thematic_rank, wargames_rank]
Index: []

In [32]:
df_bgr2 = pd.read_csv('.\\.venv\\data\\boardgames_ranks.csv')
df_bgr2.head(20)

,id,name,yearpublished,rank,bayesaverage,average,usersrated,is_expansion,abstracts_rank,cgs_rank,childrensgames_rank,familygames_rank,partygames_rank,strategygames_rank,thematic_rank,wargames_rank
0,224517,Brass: Birmingham,2018,1,8.41277,8.59213,48001,0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
1,161936,Pandemic Legacy: Season 1,2015,2,8.37571,8.52498,54148,0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN
2,174430,Gloomhaven,2017,3,8.34398,8.57972,63128,0,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN
3,342942,Ark Nova,2021,4,8.33959,8.53505,46382,0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
4,233078,Twilight Imperium: Fourth Edition,2017,5,8.23662,8.59240,24556,0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,NaN
5,316554,Dune: Imperium,2020,6,8.23137,8.43403,47922,0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN
6,167791,Terraforming Mars,2016,7,8.20734,8.35483,101433,0,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN
7,115746,War of the Ring: Second Edition,2011,8,8.19064,8.54570,22008,0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0
8,187645,Star Wars: Rebellion,2016,9,8.16964,8.41835,33163,0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
9,291457,Gloomhaven: Jaws of the Lion,2020,10,8.15191,8.42294,35486,0,NaN,NaN,NaN,NaN,NaN,9.0,7.0,NaN
10,162886,Spirit Island,2017,11,8.14533,8.34396,53527,0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN
11,220308,Gaia Project,2017,12,8.10852,8.37069,27905,0,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN
12,12333,Twilight Struggle,2005,13,8.06464,8.24366,49353,0,NaN,NaN,NaN,NaN,NaN,13.0,NaN,2.0
13,182028,Through the Ages: A New Story of Civilization,2015,14,8.04992,8.27934,32227,0,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN
14,193738,Great Western Trail,2016,15,8.01832,8.18564,41424,0,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN
15,84876,The Castles of Burgundy,2011,16,8.01596,8.14192,63447,0,NaN,NaN,NaN,NaN,NaN,17.0,NaN,NaN
16,169786,Scythe,2016,17,7.98308,8.13502,85161,0,NaN,NaN,NaN,NaN,NaN,22.0,NaN,NaN
17,246900,Eclipse: Second Dawn for the Galaxy,2020,18,7.97833,8.44890,14252,0,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN
18,173346,7 Wonders Duel,2015,19,7.97053,8.09413,97067,0,NaN,NaN,NaN,NaN,NaN,23.0,NaN,NaN
19,28720,Brass: Lancashire,2007,20,7.96312,8.19593,25338,0,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN

In [35]:
zerorank = df_bgr2[(df_bgr2['rank'] == 0)].index
df_bgr_nozero = pd.DataFrame(df_bgr2.drop(zerorank, inplace = True))
df_bgr2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27288 entries, 0 to 27287
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   27288 non-null  int64
 1   name                 27288 non-null  object
 2   yearpublished        27288 non-null  int64
 3   rank                 27288 non-null  int64
 4   bayesaverage         27288 non-null  float64
 5   average              27288 non-null  float64
 6   usersrated           27288 non-null  int64
 7   is_expansion         27288 non-null  int64
 8   abstracts_rank       1424 non-null   float64
 9   cgs_rank             362 non-null    float64
 10  childrensgames_rank  1073 non-null   float64
 11  familygames_rank     3314 non-null   float64
 12  partygames_rank      912 non-null    float64
 13  strategygames_rank   2992 non-null   float64
 14  thematic_rank        1671 non-null   float64
 15  wargames_rank        4311 non-null   float64
dtypes: float64(10), int64(5), object(1)
memory usage: 3.3+ MB

In [37]:
df_bgr_nozero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame